### PR TITLE
Small fixes in sys

### PR DESCRIPTION
**Pull request by gkoz**

### CODE REVIEW

**Comment by EPashkin** [comment]
Alias `GType` defined in glib and gobject, I don't like `ignore` it in gobject, as it comment all `*_get_type` in normal mode. Seems this need be hardcoded.

**Comment by EPashkin** [comment]
And for `gdk_pixbuf` not sure we needed rename, it may needed apply `fix_namespace` in too many places (at minumum in package naming). But we can stay with this until really problem occurs.

**Comment by EPashkin** [comment]
Or we can just change `crate_name` to apply `snake_case` after lowering first 2-3 chars.

**Comment by EPashkin** [comment]
About `GType`: may be we just needed new status `dont_declare`

**Comment by gkoz** [comment]
It seems we can ignore `GType` in `glib-sys` and either add the `gobject` import in other crates or always qualify it in hardcoded references. It likely doesn't belong in `Fundamental`.

**Comment by gkoz** [comment]
Didn't notice that `GLib` actually references `GType` as well. So it's not that simple.

**Comment by EPashkin** [comment]
Can you do it in this PR with rebasing?

**Comment by gkoz** [comment]
On it.

**Comment by EPashkin** [comment]
Don't forget about `crate_name` it you accept https://github.com/gkoz/gir/pull/68#issuecomment-121814536

**Comment by gkoz** [comment]
> Don't forget about `crate_name` it you accept #68 (comment)

Here, not sure if this change conflicts with the other use of `crate_name`.

**Comment by EPashkin** [comment]
Can you add test for crate_name("GdkPixbuf")?

**Comment by gkoz** [comment]
@homu r+

**Comment by EPashkin** [comment]
Don't see bad changes in gtk generation. Compiling stops only on gdk-sys, seems this better fixed before
```
D:\eap\rust\0\gdk\gdk-sys\src\lib.rs:16:40: 16:45 error: unresolved import `glib_ffi::gsize`. There is no `gsize` in `glib_ffi`
D:\eap\rust\0\gdk\gdk-sys\src\lib.rs:16 pub use glib_ffi::{gboolean, gpointer, gsize, GType};
```

**Comment by EPashkin** [comment]
IMHO better abort Homu, and fix `gsize`

**Comment by EPashkin** [comment]
Seems gsize just needed include in static::only_for_glib

**Comment by EPashkin** [comment]
Was wrong, seems it currently replaced to `size_t` by generator.
Then no problem

**Comment by gkoz** [comment]
I was away :) We should add the other libs to the tests.

**Comment by EPashkin** [comment]
I currently do gio

**Comment by EPashkin** [comment]
You get message about changes in https://github.com/gkoz/gir/issues/29 header?

**Comment by gkoz** [comment]
Building every crate is wasteful, there should be a test crate that depends on the others.

**Comment by EPashkin** [comment]
So build only crates, that last in build order? At end it will be only gtk

**Comment by EPashkin** [comment]
Then we need change test.sh to 2 setting, LIBS and BUILD?

**Comment by gkoz** [comment]
> You get message about changes in #29 header?

No, missed that.
